### ISSUE TITLE
SoC AssertionErrors due to floating point inaccuracy

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/spice_ev#7]
I'm getting `Consumption too high...` and `Initial charge for {} is not sufficient...` which is obviously caused by floating point inaccuracy (e.g. ineq. like `1.0000000000000002 <= 1 + 0.0`).

I see 2 ways to overcome this:
1. Use same rounding precision in simBEV and spiceEV: this might be hard to maintain and not really fail-safe.
2. Use rounded values in sanity checks. I'd propose to go this way and prepared a fix in #8

**Comment by nesnoj** [comment]
We have the very same problem here:
Running 
```
python simulate.py -s greedy -m 1 -v -o x.csv x.json
```
with [simbev_test.json.TXT](https://github.com/rl-institut/spice_ev/files/6631743/simbev_test.json.TXT) gives
```
 ******************************************
SOC of vehicle phev_medium_02670_standing_t should not be negative.                         SOC is -9.177786665759413e-06, soc_delta was -100.0
Aborting simulation in timestep 900 (2021-01-13 08:45:00+01:00)
Traceback (most recent call last):
  File "/home/nesnoj/git-repos/rl-institut/spice_ev/src/scenario.py", line 74, in run
    res = strat.step(event_steps[step_i])
  File "/home/nesnoj/git-repos/rl-institut/spice_ev/src/strategies/greedy.py", line 25, in step
    super().step(event_list)
  File "/home/nesnoj/git-repos/rl-institut/spice_ev/src/strategy.py", line 88, in step
    assert compare_rounded(vehicle.battery.soc, op.ge, 0, dec=5), (
AssertionError: SOC of vehicle phev_medium_02670_standing_t should not be negative.                         SOC is -9.177786665759413e-06, soc_delta was -100.0
Costs: 0.49 €
Renewable energy feed-in: 0 kW, unused: 0 kW (0%)
Done. Create plots...
```
The deviation is only -9.177786665759413e-06 which I assume to be a fp accuracy issue again?! I'd apply the same function as introduced in #8 with dec=4.
What do you think, @stefansc1 ?
